import { Job, JobProvider } from "./types";

export const dummyJobProviders: JobProvider[] = [
    {
        jobProvider: "LinkedIn",
        url: "https://www.linkedin.com/jobs/view/1"
    },
    {
        jobProvider: "Indeed",
        url: "https://www.indeed.com/viewjob?jk=1"
    }
];

export const dummyJobs: Job[] = [
    {
        id: "1",
        title: "Web Developer - Freelance",
        company: "Twine",
        description: "We are looking for a skilled Web Developer to join our freelance team. You'll be working on a variety of projects, creating responsive websites for our clients. Experience with HTML, CSS, JavaScript, and modern frameworks is required. Our mission is to connect businesses with talented freelancers for critical projects.",
        image: "https://images.unsplash.com/photo-1542744095-291d1f67b221",
        location: "Remote",
        employmentType: "Freelance",
        datePosted: "15 hours ago",
        salaryRange: "$40/hr",
        jobProviders: dummyJobProviders,
        type: 'Contractor',
        category: 'Popular'
    },
    {
        id: "2",
        title: "Software Engineer",
        company: "Google",
        description: "Google is seeking a talented Software Engineer to develop and maintain innovative software solutions. You'll collaborate with cross-functional teams and contribute to various stages of the development lifecycle. Proficiency in C++, Java, or Python is preferred. Join us in making a significant impact through technology.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475",
        location: "Mountain View, CA",
        employmentType: "Full-time",
        datePosted: "2 days ago",
        salaryRange: "$120k - $150k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Popular'
    },
    {
        id: "3",
        title: "Data Scientist",
        company: "Facebook",
        description: "We are looking for a Data Scientist to analyze large sets of data and provide actionable insights to our team. You will work closely with product managers and engineers to understand data needs and develop data-driven solutions. Your work will help shape the future of our products and services.",
        image: "https://images.unsplash.com/photo-1517433456452-f9633a875f6f",
        location: "Menlo Park, CA",
        employmentType: "Full-time",
        datePosted: "3 days ago",
        salaryRange: "$130k - $160k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Popular'
    },
    {
        id: "4",
        title: "UI/UX Designer",
        company: "Apple",
        description: "Design intuitive and engaging user interfaces for our software products. Collaborate with engineers and product managers to create user-centered designs. Proficiency in Sketch, Figma, or Adobe XD is required. Your designs will enhance user experiences across various devices.",
        image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
        location: "Cupertino, CA",
        employmentType: "Full-time",
        datePosted: "1 week ago",
        salaryRange: "$90k - $110k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "5",
        title: "Project Manager",
        company: "Microsoft",
        description: "Lead software development projects from concept to completion. Ensure projects are delivered on time and within budget. Strong organizational and communication skills are essential. Your leadership will drive successful project outcomes.",
        image: "https://images.unsplash.com/photo-1521791136064-7986c2920216",
        location: "Redmond, WA",
        employmentType: "Full-time",
        datePosted: "5 days ago",
        salaryRange: "$110k - $130k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Popular'
    },
    {
        id: "6",
        title: "Backend Developer",
        company: "Amazon",
        description: "Develop and maintain server-side logic. Ensure high performance and responsiveness to requests from the front-end. Experience with Node.js, Java, or Python is required. Join our team and help build scalable backend solutions.",
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        location: "Seattle, WA",
        employmentType: "Full-time",
        datePosted: "2 weeks ago",
        salaryRange: "$100k - $120k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "7",
        title: "Frontend Developer",
        company: "Netflix",
        description: "Build and maintain user-facing features for our web applications. Ensure the technical feasibility of UI/UX designs. Experience with React, Angular, or Vue.js is preferred. Help us deliver engaging user experiences across all platforms.",
        image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        location: "Los Gatos, CA",
        employmentType: "Full-time",
        datePosted: "3 weeks ago",
        salaryRange: "$95k - $115k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "8",
        title: "Mobile Developer",
        company: "Spotify",
        description: "Develop and maintain mobile applications for iOS and Android platforms. Work closely with designers and product managers. Experience with Swift, Kotlin, or React Native is required. Create apps that bring music to millions of users worldwide.",
        image: "https://images.unsplash.com/photo-1556155092-8707de31f9c4",
        location: "New York, NY",
        employmentType: "Full-time",
        datePosted: "1 month ago",
        salaryRange: "$105k - $125k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Popular'
    },
    {
        id: "9",
        title: "DevOps Engineer",
        company: "Slack",
        description: "Automate and streamline our operations and processes. Build and maintain tools for deployment, monitoring, and operations. Experience with AWS, Docker, and Kubernetes is preferred. Enhance our infrastructure to support our growing user base.",
        image: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7",
        location: "San Francisco, CA",
        employmentType: "Full-time",
        datePosted: "3 weeks ago",
        salaryRange: "$115k - $135k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "10",
        title: "System Administrator",
        company: "Cisco",
        description: "Maintain and support the infrastructure and systems. Monitor system performance and troubleshoot issues. Experience with Linux, Windows Server, and network configurations is required. Ensure the reliability and security of our IT systems.",
        image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
        location: "San Jose, CA",
        employmentType: "Full-time",
        datePosted: "1 month ago",
        salaryRange: "$85k - $105k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Popular'
    },
    {
        id: "11",
        title: "Network Engineer",
        company: "AT&T",
        description: "Design, implement, and manage network infrastructure. Ensure the network is secure, reliable, and optimized. Experience with Cisco or Juniper networks is preferred. Support our growing network infrastructure.",
        image: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7",
        location: "Dallas, TX",
        employmentType: "Full-time",
        datePosted: "2 weeks ago",
        salaryRange: "$95k - $115k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Popular'
    },
    {
        id: "12",
        title: "Cybersecurity Analyst",
        company: "IBM",
        description: "Protect our systems and data from cyber threats. Monitor networks for security breaches and investigate incidents. Experience with SIEM, firewalls, and intrusion detection systems is required. Help us safeguard our digital assets.",
        image: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87",
        location: "Armonk, NY",
        employmentType: "Full-time",
        datePosted: "1 week ago",
        salaryRange: "$110k - $130k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "13",
        title: "Database Administrator",
        company: "Oracle",
        description: "Manage and maintain our database systems. Ensure data integrity, security, and availability. Experience with Oracle, MySQL, or PostgreSQL databases is required. Optimize database performance for our applications.",
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        location: "Redwood City, CA",
        employmentType: "Full-time",
        datePosted: "2 weeks ago",
        salaryRange: "$95k - $115k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Popular'
    },
    {
        id: "14",
        title: "IT Support Specialist",
        company: "Dell",
        description: "Provide technical support to our employees. Troubleshoot hardware and software issues. Experience with Windows, macOS, and common enterprise applications is preferred. Ensure smooth IT operations.",
        image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df",
        location: "Round Rock, TX",
        employmentType: "Full-time",
        datePosted: "2 weeks ago",
        salaryRange: "$50k - $70k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "15",
        title: "Cloud Solutions Architect",
        company: "Adobe",
        description: "Design and implement cloud-based solutions for our clients. Work with cross-functional teams to ensure successful cloud deployments. Experience with AWS, Azure, or Google Cloud is required.",
        image: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87",
        location: "San Jose, CA",
        employmentType: "Full-time",
        datePosted: "1 week ago",
        salaryRange: "$120k - $140k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Popular'
    },
    {
        id: "16",
        title: "Product Manager",
        company: "Tesla",
        description: "Lead the development and launch of new products. Work closely with engineering, design, and marketing teams to ensure product success. Strong leadership and project management skills are required.",
        image: "https://images.unsplash.com/photo-1497493292307-31c376b6e479",
        location: "Palo Alto, CA",
        employmentType: "Full-time",
        datePosted: "3 days ago",
        salaryRange: "$110k - $130k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Popular'
    },
    {
        id: "17",
        title: "Technical Writer",
        company: "IBM",
        description: "Create and maintain technical documentation for our products. Work with engineers and product managers to ensure accuracy and clarity. Strong writing and communication skills are required.",
        image: "https://images.unsplash.com/photo-1497493292307-31c376b6e479",
        location: "Austin, TX",
        employmentType: "Full-time",
        datePosted: "1 week ago",
        salaryRange: "$70k - $90k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "18",
        title: "Graphic Designer",
        company: "Adobe",
        description: "Create visually appealing designs for our digital and print materials. Work with marketing and product teams to ensure brand consistency. Proficiency in Adobe Creative Suite is required.",
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        location: "San Francisco, CA",
        employmentType: "Full-time",
        datePosted: "4 days ago",
        salaryRange: "$60k - $80k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "19",
        title: "Marketing Specialist",
        company: "HubSpot",
        description: "Develop and implement marketing strategies to promote our products and services. Work with the sales team to generate leads and increase revenue. Experience with digital marketing and analytics tools is preferred.",
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5",
        location: "Cambridge, MA",
        employmentType: "Full-time",
        datePosted: "5 days ago",
        salaryRange: "$70k - $90k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Popular'
    },
    {
        id: "20",
        title: "Network Security Engineer",
        company: "Cisco",
        description: "Implement and manage security measures for our network infrastructure. Monitor for security breaches and respond to incidents. Experience with firewalls, VPNs, and SIEM tools is required.",
        image: "https://images.unsplash.com/photo-1581091870566-4385c05f37f2",
        location: "San Jose, CA",
        employmentType: "Full-time",
        datePosted: "2 days ago",
        salaryRange: "$110k - $130k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "21",
        title: "Systems Engineer",
        company: "VMware",
        description: "Design and implement complex systems for our clients. Provide technical support and troubleshooting. Experience with virtualization and cloud technologies is required.",
        image: "https://images.unsplash.com/photo-1542831371-29b0f74f9713",
        location: "Palo Alto, CA",
        employmentType: "Full-time",
        datePosted: "1 week ago",
        salaryRange: "$100k - $120k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "22",
        title: "Data Engineer",
        company: "Twitter",
        description: "Build and maintain data pipelines. Ensure data quality and availability. Experience with SQL, Python, and big data technologies is preferred.",
        image: "https://images.unsplash.com/photo-1556155092-8707de31f9c4",
        location: "San Francisco, CA",
        employmentType: "Full-time",
        datePosted: "3 days ago",
        salaryRange: "$120k - $140k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "23",
        title: "Full Stack Developer",
        company: "Dropbox",
        description: "Develop and maintain web applications. Work on both the front-end and back-end. Experience with JavaScript, Node.js, and React is required.",
        image: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87",
        location: "San Francisco, CA",
        employmentType: "Full-time",
        datePosted: "2 weeks ago",
        salaryRange: "$110k - $130k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "24",
        title: "Machine Learning Engineer",
        company: "OpenAI",
        description: "Develop and implement machine learning models. Work with large datasets and complex algorithms. Experience with Python and TensorFlow is required.",
        image: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7",
        location: "San Francisco, CA",
        employmentType: "Full-time",
        datePosted: "1 week ago",
        salaryRange: "$130k - $150k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "25",
        title: "Technical Support Engineer",
        company: "Atlassian",
        description: "Provide technical support to our customers. Troubleshoot and resolve issues with our software products. Strong communication skills and technical knowledge are required.",
        image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        location: "San Francisco, CA",
        employmentType: "Full-time",
        datePosted: "3 days ago",
        salaryRange: "$70k - $90k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "26",
        title: "Solutions Architect",
        company: "Salesforce",
        description: "Design and implement solutions for our clients. Work with sales and engineering teams to ensure successful deployments. Experience with Salesforce and cloud technologies is preferred.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475",
        location: "San Francisco, CA",
        employmentType: "Full-time",
        datePosted: "2 weeks ago",
        salaryRange: "$120k - $140k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "27",
        title: "Mobile Application Developer",
        company: "Uber",
        description: "Develop and maintain mobile applications for our platform. Ensure high performance and user experience. Experience with Swift, Kotlin, or React Native is required.",
        image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df",
        location: "San Francisco, CA",
        employmentType: "Full-time",
        datePosted: "1 week ago",
        salaryRange: "$110k - $130k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "28",
        title: "DevOps Engineer",
        company: "Pinterest",
        description: "Automate and streamline our operations and processes. Build and maintain tools for deployment, monitoring, and operations. Experience with AWS, Docker, and Kubernetes is preferred.",
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        location: "San Francisco, CA",
        employmentType: "Full-time",
        datePosted: "3 days ago",
        salaryRange: "$115k - $135k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "29",
        title: "Cloud Engineer",
        company: "AWS",
        description: "Design, develop, and manage cloud infrastructure. Ensure scalability, performance, and security. Experience with AWS services is required.",
        image: "https://images.unsplash.com/photo-1497493292307-31c376b6e479",
        location: "Seattle, WA",
        employmentType: "Full-time",
        datePosted: "2 days ago",
        salaryRange: "$120k - $140k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "30",
        title: "Data Analyst",
        company: "Tableau",
        description: "Analyze and interpret data to provide insights for our business. Create reports and visualizations. Experience with SQL and Tableau is preferred.",
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        location: "Seattle, WA",
        employmentType: "Full-time",
        datePosted: "1 week ago",
        salaryRange: "$85k - $105k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "31",
        title: "Product Designer",
        company: "Canva",
        description: "Create intuitive and engaging user interfaces for our products. Work with product managers and engineers to bring designs to life. Proficiency in Sketch, Figma, or Adobe XD is required.",
        image: "https://images.unsplash.com/photo-1521791136064-7986c2920216",
        location: "Sydney, Australia",
        employmentType: "Full-time",
        datePosted: "3 days ago",
        salaryRange: "$90k - $110k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    },
    {
        id: "32",
        title: "Sales Engineer",
        company: "Oracle",
        description: "Support the sales team by providing technical expertise. Assist with product demonstrations and technical presentations. Experience with enterprise software is preferred.",
        image: "https://images.unsplash.com/photo-1542744095-291d1f67b221",
        location: "Redwood City, CA",
        employmentType: "Full-time",
        datePosted: "2 weeks ago",
        salaryRange: "$110k - $130k",
        jobProviders: dummyJobProviders,
        type: 'Full-time',
        category: 'Nearby'
    }
];